// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DaterangeController from "./daterange_controller"
application.register("daterange", DaterangeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
